### ISSUE TITLE
Example unable to build for device (iPad)

### ISSUE THREAD

**Issue by Sam-Hoult** [Traede/react-native-socket-mobile#1]
Firstly, thank-you so much for building this bridge!!

My issue is I can build and run the example for the simulator, however when I try to run on a device I get errors:
```
In file included from /Users/samhoult/web/learning/react-native-socket-mobile/node_modules/react-native/Libraries/Vibration/RCTVibration.m:10:
/Users/samhoult/web/learning/react-native-socket-mobile/node_modules/react-native/Libraries/Vibration/RCTVibration.h:10:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

The reason I'm trying the example is because the `pod install` step breaks my production app so wanted to start from basics with this.

**Comment by Sam-Hoult** [comment]
Solved.
It was a problem with my build scheme missing react.

I added it through: Product > Scheme > Edit Scheme > Build > + > React

![image](https://user-images.githubusercontent.com/1436841/38720086-b8e69012-3ea9-11e8-8b51-fec9d16a8321.png)

**Comment by ferrannp** [comment]
Yeah! The example has this problems sometimes, you need to build React separately (it does not happen if you just use the library in your project).

**Comment by Sam-Hoult** [comment]
I'd guess this to be the change that fixed it when adding it to the build process it was previously missing:
![image](https://user-images.githubusercontent.com/1436841/38747582-2957b8d4-3f00-11e8-89b2-94c20a5ff42a.png)
